### ISSUE TITLE
Feature request: workflow can open projects in subfolders

### ISSUE THREAD

**Issue by natterstefan** [bjrnt/alfred-project-manager#10]
Hi @bjrnt,

thanks for the workflow. It looks promising and is exactly what I need. Still, I have some trouble.

My folder looks similar to:

```
./projects
./projects/company
./projects/company/project-a
./projects/company/project-b
```

When I enter `pm company/project-a` it says:

![image](https://user-images.githubusercontent.com/1043668/84059620-361bee00-a9bb-11ea-89a0-d223332c0cac.png)

Thanks for your help and feedback.

**Comment by bjrnt** [comment]
Hi @natterstefan,

Thanks for the feedback! Since the workflow only supports a single project directory without recursive traversal, I think it'd be appropriate to look at this more of as a feature request than a bug. 

The reason recursive traversal isn't enabled by default is that projects will often contain deeply nested folder structures and the workflow doesn't have a way of figuring out which folders are projects and which are just normal folders.

To allow for namespaced projects as in your case, I am considering adding a recursive traversal option that would look for folders containing `.git` subfolders, indicating that they're version controlled. For example, if `company/project-a/.git` exists, `company/project-a` would show as an autocomplete candidate. Would that work for your usecase?

**Comment by natterstefan** [comment]
Hi @bjrnt,

thanks for your feedback. I'm sorry I called this a "Bug", as you said this is indeed a "Feature request" instead. The title was changed accordingly.

That would help, yes.

**Comment by bjrnt** [comment]
Hi @natterstefan ,

I've updated the workflow to include the functionality you requested. It's available as version 1.3.0 [here](https://github.com/bjrnt/alfred-project-manager/releases).

For your particular use case, I'd recommend setting `MAX_PROJECT_DEPTH` to `1` to allow for workspaced projects and `REQUIRE_DOTGIT` to `true` to avoid false positives in the search results. 

With those options, I was able to reproduce your desired output:
<img width="588" alt="Screenshot 2020-06-11 at 17 23 05" src="https://user-images.githubusercontent.com/484114/84405314-4379e800-ac08-11ea-84ca-3513fc5f7663.png">

Hope you can give it a try and let me know how it works! :)

**Comment by natterstefan** [comment]
Awesome, I'll test it later and give you feedback! Thanks. That was fast. :)

**Comment by natterstefan** [comment]
Hi @bjrnt,

I just downloaded the latest version [1.3.0](https://github.com/bjrnt/alfred-project-manager/releases/tag/1.3.0) and it works. Thank you!
